# This workflow generates the output and pushes it to master branch

name: Generate Output

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: npm install -g markdown-table-cli

    - name: Run steamcmd_appid_servers.sh
      run: ./steamcmd_appid_servers.sh

    - name: Push to master branch
      uses: Automattic/action-commit-to-branch@master
      with:
        branch: 'master'
        commit_message: 'GitHub Actions Build master'
      env:
        GITHUB_TOKEN: ${{ secrets.STEAMCMD_APPID_LIST }} # Required
